name = "unera-2"
compatibility_date = "2024-11-01"

# =====================================================
# D1 DATABASE (UNERA)
# =====================================================
[[d1_databases]]
binding = "DB"
database_name = "unera"
database_id = "fd656687-7a46-4250-849a-28eb60ea9173"

# =====================================================
# DURABLE OBJECT â€“ REAL-TIME FEED
# =====================================================
[durable_objects]
bindings = [
  { name = "LIVE_FEED_DO", class_name = "LiveFeed" }
]

# =====================================================
# DURABLE OBJECT MIGRATIONS
# =====================================================
[[migrations]]
tag = "v1"
new_classes = ["LiveFeed"]
